language: node_js
os:
  - linux
  - windows

env:
  global:
    - APM_TEST_PACKAGES="language-svg"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

dist: trusty

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev
